.TH BUTHEAD "1" "April 1" "buthead (latzutils)" "User Commands"
.SH NAME
buthead \- copies all but the first few lines
.SH SYNOPSIS
.BI buthead \ count
.SH EXAMPLE
.B buthead
5 <file-with-5-line-header >file-without-header
.SH DESCRIPTION
.B Buthead
copies all but the first
.I count
lines of stdin to stdout.
.SH DIAGNOSTICS
Terminates gracefully if EOF encountered within first
.I count
lines.
.SH AUTHOR
Written by Barak A. Pearlmutter on April 1.
.SH BUGS
Functionality overlaps with
.BI tail\ -n\ + count
or
.BI awk\ '(NR> count )'
.SH SEE\ ALSO
head(1), tail(1)
