.TH BUTHEAD 1 CMU-Mach "April 1, 1988"
.SH NAME
buthead \- copies all but the first few lines
.SH SYNOPSIS
.B buthead
count
.SH EXAMPLE
.B buthead
5 <file-with-5-line-header >file-without-header
.SH DESCRIPTION
.I Buthead
copies all but the first
.I count
lines of its standard input to its standard output.
.SH DIAGNOSTICS
Terminates gracefully if EOF encountered within first
.I count
lines.
.SH AUTHOR
Written by Barak A. Pearlmutter on April 1.
.SH BUGS
Functionality overlaps with
.I tail +count
.SH SEE\ ALSO
head(1), tail(1)
